[deployment]
run = ["node", "dist/index.js"]
deploymentTarget = "cloudrun"
buildCommand = "node deploy-size-optimized.cjs"

[env]
NODE_ENV = "production"
PORT = "5000"

[[ports]]
localPort = 5000
externalPort = 80